[package]
name = "darwinia-phragmen"
version = "0.5.3"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "PHRAGMENT primitives"
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia/"

[dependencies]
# crates
serde = { version = "1.0.106", optional = true, features = ["derive"] }
# darwinia
darwinia-support = { default-features = false, path = "../../frame/support" }
# substrate
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", rev = "d1238423a3093eb64df90c0eebdbf504c8df56dd" }
sp-std = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", rev = "d1238423a3093eb64df90c0eebdbf504c8df56dd" }

[dev-dependencies]
# crates
rand = { version = "0.7.3" }
# substrate
sp-io = { git = "https://github.com/darwinia-network/substrate.git", rev = "d1238423a3093eb64df90c0eebdbf504c8df56dd" }
substrate-test-utils = { git = "https://github.com/darwinia-network/substrate.git", rev = "d1238423a3093eb64df90c0eebdbf504c8df56dd" }

[features]
default = ["std"]
std = [
	# crates
	"serde",
	# darwinia
	"darwinia-support/std",
	# substrate
	"sp-runtime/std",
	"sp-std/std",
]
