[package]
name = "darwinia-phragmen"
version = "0.5.1"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "PHRAGMENT primitives"
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia/"

[dependencies]
# crates
serde = { version = "1.0.101", optional = true, features = ["derive"] }
# darwinia
darwinia-support = { default-features = false, path = "../../frame/support" }
# substrate
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "ci-release-2.0.0-alpha.5+6" }
sp-std = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "ci-release-2.0.0-alpha.5+6" }

[dev-dependencies]
# crates
rand = { version = "0.7.2" }
# substrate
sp-io = { git = "https://github.com/darwinia-network/substrate.git", tag = "ci-release-2.0.0-alpha.5+6" }
substrate-test-utils = { git = "https://github.com/darwinia-network/substrate.git", tag = "ci-release-2.0.0-alpha.5+6" }

[features]
default = ["std"]
std = [
	# crates
	"serde",
	# darwinia
	"darwinia-support/std",
	# substrate
	"sp-runtime/std",
	"sp-std/std",
]
