[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "BN128 precompiles for EVM pallet."
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-evm-precompile-bn128"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "1.3.0"


[dependencies]
# crates
bn                       = { default-features = false, package = "substrate-bn", version = "0.5" }
darwinia-evm-primitives  = { default-features = false, path = "../../../../../primitives/evm" }
evm                      = { default-features = false, git = "https://github.com/darwinia-network/evm.git", branch = "darwinia", features = ["with-codec"] }
# substrate
sp-core                  = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-io                    = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }

[features]
default = ["std"]

std = [
	"crates-std",
	"substrate-std",
]

crates-std = [
	"darwinia-evm-primitives/std",
	"evm/std",
]

substrate-std = [
	"sp-core/std",
	"sp-io/std",
]
