[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "FRAME pallet to issuing Ethereum assets"
edition     = "2021"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "from-ethereum-issuing"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "2.7.1"

[dependencies]
# crates.io
array-bytes = { version = "1.4" }
codec       = { package = "parity-scale-codec", version = "2.1", default-features = false, features = ["derive"] }
log         = { version = "0.4" }
sha3        = { version = "0.9", default-features = false }
# darwinia-network
darwinia-bridge-ethereum  = { default-features = false, path = "../../../bridge/ethereum" }
darwinia-evm              = { default-features = false, path = "../../../evm" }
darwinia-relay-primitives = { default-features = false, path = "../../../../primitives/relay" }
darwinia-support          = { default-features = false, path = "../../../support" }
dp-contract               = { default-features = false, path = "../../../../primitives/contract" }
dp-evm                    = { default-features = false, path = "../../../../primitives/evm" }
dvm-ethereum              = { default-features = false, path = "../../../dvm" }
ethereum-primitives       = { default-features = false, features = ["full-codec"], path = "../../../../primitives/ethereum" }
# paritytech
frame-benchmarking = { optional = true, default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.8" }
frame-support      = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.8" }
frame-system       = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.8" }
sp-runtime         = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.8" }
sp-std             = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.8" }

[features]
default = ["std"]

std = [
	# crates.io
	"codec/std",
	"sha3/std",
	# darwinia-network
	"darwinia-bridge-ethereum/std",
	"darwinia-evm/std",
	"ethereum-primitives/std",
	"darwinia-relay-primitives/std",
	"darwinia-support/std",
	"dp-contract/std",
	"dp-evm/std",
	"dvm-ethereum/std",
	# paritytech
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"sp-runtime/std",
	"sp-std/std",
]

runtime-benchmarks = ["frame-benchmarking"]
