[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "FRAME pallet to issuing Ethereum assets"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-ethereum-issuing"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "1.0.0"

[dependencies]
# crates
codec      = { package = "parity-scale-codec", version = "1.3.5", default-features = false, features = ["derive"] }
serde      = { version = "1.0.118", optional = true }
serde_json = { version = "1.0.61", optional = true }
# darwinia
darwinia-evm             = { default-features = false, path = "../../../evm" }
darwinia-evm-primitives  = { default-features = false, path = "../../../../primitives/evm" }
darwinia-evm-precompile = { default-features = false, path = "../../../evm/precompile" }
dvm-ethereum = { default-features = false, path = "../../../dvm" }
darwinia-relay-primitives = { default-features = false, path = "../../../../primitives/relay" }
ethereum-types = { default-features = false, version = "0.9.0" }
rustc-hex      = { default-features = false, version = "2.1.0" }
hex                      = { default-features = false, version = "0.4" }
darwinia-ethereum-issuing-contract = { default-features = false, path = "contract" }
ethereum-primitives       = { default-features = false, path = "../../../../primitives/ethereum-primitives" }
# substrate
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
darwinia-support = { default-features = false, path = "../../../support" }
frame-system  = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-io         = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-runtime    = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-std        = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }

[dev-dependencies]
# darwinia
darwinia-balances              = { path = "../../../../frame/balances" }
darwinia-ethereum-linear-relay = { path = "../linear-relay" }
darwinia-ethereum-relay        = { features = ["deserialize"], path = "../relay" }
darwinia-relay-primitives      = { path = "../../../../primitives/relay" }
darwinia-relayer-game          = { path = "../../relayer-game" }
darwinia-staking               = { path = "../../../../frame/staking" }
ethereum-primitives            = { features = ["deserialize"], path = "../../../../primitives/ethereum-primitives" }

[features]
default = ["std"]

std = [
	"substrate-std",
    "crates-std",
    "darwinia-std",
]

crates-std    = [
	"codec/std",
	"ethereum-types/std",
    "rustc-hex/std",
	"serde",
	"serde_json",
]

darwinia-std = [
	"darwinia-evm/std",
    "darwinia-evm-precompile/std",
    "dvm-ethereum/std",
    "darwinia-evm-primitives/std",
	"darwinia-support/std",
    "darwinia-ethereum-issuing-contract/std",
	"ethereum-primitives/std",
	"darwinia-relay-primitives/std",
]

substrate-std = [
	"frame-support/std",
	"frame-system/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
