[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "FRAME pallet to issuing Ethereum assets"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-ethereum-issuing"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "2.5.0"

[dependencies]
# crates
codec          = { package = "parity-scale-codec", version = "2.1.1", default-features = false, features = ["derive"] }
ethereum-types = { default-features = false, version = "0.11.0" }
log            = { version = "0.4.14" }
serde          = { version = "1.0.126", optional = true }
serde_json     = { version = "1.0.64", optional = true }
# darwinia
darwinia-ethereum-issuing-contract = { default-features = false, path = "contract" }
darwinia-evm                       = { default-features = false, path = "../../../evm" }
darwinia-relay-primitives          = { default-features = false, path = "../../../../primitives/relay" }
darwinia-support                   = { default-features = false, path = "../../../support" }
dp-evm                             = { default-features = false, path = "../../../../primitives/evm" }
dvm-ethereum                       = { default-features = false, path = "../../../dvm" }
ethereum-primitives                = { default-features = false, path = "../../../../primitives/ethereum-primitives" }
# substrate
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
frame-system  = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-runtime    = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-std        = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "s2s" }

[features]
default = ["std"]

std = [
	"substrate-std",
	"crates-std",
	"darwinia-std",
]

crates-std = [
	"codec/std",
	"ethereum-types/std",
	"serde",
	"serde_json",
]

darwinia-std = [
	"darwinia-evm/std",
	"darwinia-ethereum-issuing-contract/std",
	"ethereum-primitives/std",
	"darwinia-relay-primitives/std",
	"darwinia-support/std",
	"dp-evm/std",
	"dvm-ethereum/std",
]

substrate-std = [
	"frame-support/std",
	"frame-system/std",
	"sp-runtime/std",
	"sp-std/std",
]
