[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "FRAME pallet to issuing Ethereum assets"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-ethereum-issuing"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "2.1.0"

[dependencies]
# crates
codec               = { package = "parity-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
ethereum-types      = { default-features = false, version = "0.11.0" }
ethereum-primitives = { default-features = false, path = "../../../../primitives/ethereum-primitives" }
log                 = { version = "0.4.14" }
rustc-hex           = { default-features = false, version = "2.1.0" }
serde               = { version = "1.0.124", optional = true }
serde_json          = { version = "1.0.62", optional = true }
# darwinia
darwinia-evm                        = { default-features = false, path = "../../../evm" }
darwinia-ethereum-issuing-contract  = { default-features = false, path = "contract" }
darwinia-evm-precompile             = { default-features = false, path = "../../../evm/precompile" }
darwinia-relay-primitives           = { default-features = false, path = "../../../../primitives/relay" }
darwinia-support                    = { default-features = false, path = "../../../support" }
dp-evm                              = { default-features = false, path = "../../../../primitives/evm" }
dvm-ethereum                        = { default-features = false, path = "../../../dvm" }
# substrate
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "rococo-v1.2" }
frame-system  = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "rococo-v1.2" }
sp-runtime    = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "rococo-v1.2" }
sp-std        = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "rococo-v1.2" }


[features]
default = ["std"]

std = [
	"substrate-std",
    "crates-std",
    "darwinia-std",
]

crates-std    = [
    "codec/std",
    "ethereum-types/std",
    "rustc-hex/std",
    "serde",
    "serde_json",
]

darwinia-std = [
    "darwinia-evm/std",
    "darwinia-evm-precompile/std",
    "darwinia-ethereum-issuing-contract/std",
    "ethereum-primitives/std",
    "darwinia-relay-primitives/std",
    "darwinia-support/std",
    "dp-evm/std",
    "dvm-ethereum/std",
]

substrate-std = [
	"frame-support/std",
	"frame-system/std",
	"sp-runtime/std",
	"sp-std/std",
]
