[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Runtime primitives for Ethereum RPC (web3) compatibility layer for Darwinia."
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "dvm-rpc-core"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "1.3.0"

[dependencies]
# crates
codec          = { package = "parity-scale-codec", version = "1.3.5", default-features = false }
ethereum       = { version = "0.5", default-features = false, features = ["with-codec"] }
ethereum-types = { version = "0.9", default-features = false }
jsonrpc-core   = { version = "15.1.0" }
jsonrpc-derive = { version = "15.1.0" }
jsonrpc-pubsub = { version = "15.1.0" }

# darwinia
darwinia-evm            = { default-features = false, path = "../../evm" }
darwinia-evm-primitives = { default-features = false, path = "../../../primitives/evm" }
dvm-rpc-core-primitives = { default-features = false, path = "../../../primitives/dvm-rpc-core" }
# substrate
sp-api     = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", rev = "095d0f06a42b66a92f28d097499a69e3f170d59d" }
sp-core    = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", rev = "095d0f06a42b66a92f28d097499a69e3f170d59d" }
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", rev = "095d0f06a42b66a92f28d097499a69e3f170d59d" }
sp-std     = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", rev = "095d0f06a42b66a92f28d097499a69e3f170d59d" }

[features]
default = ["std"]

std = [
	"crates-std",
	"darwinia-std",
	"substrate-std",
]

crates-std    = [
	"codec/std",
	"ethereum/std",
	"ethereum-types/std",
]
darwinia-std  = [
	"darwinia-evm/std",
	"darwinia-evm-primitives/std",
]
substrate-std = [
	"sp-api/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
