[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Runtime primitives for Ethereum RPC (web3) compatibility layer for Darwinia."
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "dvm-rpc-core"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "2.2.0"

[dependencies]
# crates
codec          = { package = "parity-scale-codec", version = "2.0.1", default-features = false }
ethereum       = { version = "0.7.1", default-features = false, features = ["with-codec"] }
ethereum-types = { version = "0.11.0", default-features = false }
jsonrpc-core   = { version = "15.1.0" }
jsonrpc-derive = { version = "15.1.0" }
jsonrpc-pubsub = { version = "15.1.0" }

# darwinia
darwinia-evm = { default-features = false, path = "../../evm" }
dp-evm       = { default-features = false, path = "../../../primitives/evm" }
dp-rpc       = { default-features = false, path = "../../../primitives/rpc" }
# substrate
sp-api     = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-core    = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-std     = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }

[features]
default = ["std"]

std = [
	"crates-std",
	"darwinia-std",
	"substrate-std",
]

crates-std    = [
	"codec/std",
	"ethereum/std",
	"ethereum-types/std",
]
darwinia-std  = [
	"darwinia-evm/std",
	"dp-evm/std",
]
substrate-std = [
	"sp-api/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
