[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Runtime primitives for Ethereum RPC (web3) compatibility layer for Darwinia."
edition     = "2021"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "dvm-rpc-core"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "2.7.1"

[dependencies]
# crates.io
codec          = { package = "parity-scale-codec", version = "2.1", default-features = false }
ethereum       = { version = "0.9", default-features = false, features = ["with-codec"] }
ethereum-types = { version = "0.12", default-features = false }
futures        = { version = "0.3", features = ["compat"] }
jsonrpc-core   = { version = "15.1" }
jsonrpc-derive = { version = "15.1" }
jsonrpc-pubsub = { version = "15.1" }
serde          = { version = "1.0", features = [ "derive" ] }
serde_json     = { version = "1.0" }

# darwinia-network
darwinia-evm = { default-features = false, path = "../../evm" }
dc-tracer    = { path = "../../../client/dvm/tracer" }
dp-evm       = { default-features = false, path = "../../../primitives/evm" }
dp-rpc       = { optional = true, path = "../../../primitives/rpc" }
# paritytech
sp-api     = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.8" }
sp-core    = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.8" }
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.8" }
sp-std     = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.8" }

[features]
default = ["std"]

std = [
	# crates.io
	"codec/std",
	"ethereum/std",
	"ethereum-types/std",
	# darwinia-network
	"darwinia-evm/std",
	"dp-evm/std",
	"dp-rpc",
	# paritytech
	"sp-api/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
