[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "MODEXP precompiles for EVM pallet."
edition     = "2021"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-evm-precompile-modexp"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "2.7.1"


[dependencies]
# crates.io
dp-evm = { default-features = false, path = "../../../../../primitives/evm" }
evm    = { git = "https://github.com/darwinia-network/evm", branch = "darwinia", default-features = false, features = ["with-codec"] }
num    = { version = "0.3", default-features = false, features = ["alloc"] }
# paritytech
sp-core = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.8" }
sp-io   = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.8" }

[dev-dependencies]
hex = { version = "0.4" }

[features]
default = ["std"]

std = [
	# crates.io
	"dp-evm/std",
	"evm/std",
	"num/std",
	# paritytech
	"sp-core/std",
	"sp-io/std",
]
