[package]
name = "darwinia-eth-relay"
version = "0.5.4"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "FRAME pallet to relay Ethereum headers"
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia/"

[dependencies]
# crates
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.106", optional = true }
serde_json = { version = "1.0.51", optional = true }
# darwinia
darwinia-support = { default-features = false, path = "../../../support" }
ethash = { default-features = false, git = "https://github.com/darwinia-network/rust-ethash" }
eth-primitives = { default-features = false, path = "../../../../primitives/eth-primitives" }
merkle-patricia-trie = { default-features = false, path = "../../../../primitives/merkle-patricia-trie" }
# github
ethereum-types = { default-features = false, git = "https://github.com/darwinia-network/parity-common.git" }
rlp = { default-features = false, git = "https://github.com/darwinia-network/parity-common.git" }
# substrate
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
frame-system = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-io = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
sp-std = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }

[dev-dependencies]
# darwinia
darwinia-balances = { path = "../../../../frame/balances" }
# substrate
sp-core = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }

[features]
default = ["std"]
std = [
	# crates
	"codec/std",
	"serde",
	"serde_json",
	# darwinia
	"darwinia-support/std",
	"ethash/std",
	"eth-primitives/std",
	"merkle-patricia-trie/std",
	# github
	"ethereum-types/std",
	"ethereum-types/serialize",
	"rlp/std",
	# substrate
	"frame-support/std",
	"frame-system/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
