[package]
name = "darwinia-eth-relay"
version = "0.5.2"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "FRAME pallet to relay Ethereum headers"
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia/"

[dependencies]
# crates
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.106", optional = true }
# darwinia
ethash = { default-features = false, git = "https://github.com/darwinia-network/rust-ethash" }
eth-primitives = { default-features = false, path = "../../../../primitives/eth-primitives" }
merkle-patricia-trie = { default-features = false, path = "../../../../primitives/merkle-patricia-trie" }
# github
rlp = { default-features = false, git = "https://github.com/darwinia-network/parity-common.git" }
ethereum-types = { default-features = false, git = "https://github.com/darwinia-network/parity-common.git" }
# substrate
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.3" }
frame-system = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.3" }
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.3" }
sp-std = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.3" }
sp-io = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.3" }

[dev-dependencies]
# crates
keccak-hasher = { version = "0.15.2" }
serde_json = { version = "1.0.51" }
# darwinia
darwinia-support = { path = "../../../support" }
# substrate
sp-core = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.3" }

[features]
default = ["std"]
std = [
	# crates
	"codec/std",
	"serde",
	# darwinia
	"ethash/std",
	"eth-primitives/std",
	"merkle-patricia-trie/std",
	# github
	"rlp/std",
	"ethereum-types/std",
    "ethereum-types/serialize",
	# substrate
	"frame-support/std",
	"frame-system/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-io/std",
]
