[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
build       = "build.rs"
description = "FRAME pallet to relay Ethereum headers"
edition     = "2021"
homepage    = "https://darwinia.network"
license     = "GPL-3.0"
name        = "darwinia-bridge-ethereum"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common"
version     = "2.8.10"

[dependencies]
# crates.io
array-bytes    = { version = "1.4" }
blake2-rfc     = { version = "0.2", default-features = false }
codec          = { package = "parity-scale-codec", version = "2.3", default-features = false }
ethereum-types = { version = "0.12", default-features = false }
rlp            = { version = "0.5", default-features = false }
scale-info     = { version = "1.0", default-features = false, features = ["derive"] }
serde          = { version = "1.0", optional = true }
serde_json     = { version = "1.0", optional = true }
# darwinia-network
ckb-merkle-mountain-range = { default-features = false, git = "https://github.com/darwinia-network/merkle-mountain-range" }
darwinia-relay-primitives = { default-features = false, path = "../../../primitives/relay" }
darwinia-relayer-game     = { default-features = false, path = "../relayer-game" }
darwinia-support          = { default-features = false, path = "../../support" }
ethereum-primitives       = { default-features = false, features = ["full-codec", "full-rlp"], path = "../../../primitives/ethereum" }
# paritytech
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.2" }
frame-system  = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.2" }
sp-core       = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.2" }
sp-runtime    = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.2" }
sp-std        = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.2" }

[dev-dependencies]
# darwinia-network
darwinia-balances   = { path = "../../balances" }
ethereum-primitives = { features = ["full-serde"], path = "../../../primitives/ethereum" }
# paritytech
sp-core = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.2" }
sp-io   = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.2" }

[features]
default = ["std"]

std = [
	# crates.io
	"blake2-rfc/std",
	"codec/std",
	"ethereum-types/std",
	"rlp/std",
	"scale-info/std",
	"serde",
	"serde_json",
	# darwinia-network
	"ckb-merkle-mountain-range/std",
	"darwinia-relayer-game/std",
	"darwinia-relay-primitives/std",
	"darwinia-support/std",
	"ethereum-primitives/std",
	"ethereum-primitives/full-serde",
	# paritytech
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
