[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Issuing precompile for EVM pallet."
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-evm-precompile-issuing"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "2.2.0"

[dependencies]
# crates
evm  = { default-features = false, version = "0.25.0", features = ["with-codec"] }
# darwinia
darwinia-evm   = { default-features = false, path = "../../../"}
dp-evm         = { default-features = false, path = "../../../../../primitives/evm" }
# substrate
sp-std = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }

[features]
default = ["std"]

std = [
	"crates-std",
	"darwinia-std",
	"substrate-std",
]

crates-std = [
	"evm/std",
]

darwinia-std = [
	"darwinia-evm/std",
	"dp-evm/std",
]

substrate-std = [
	"sp-std/std",
]
