[package]
name = "darwinia-eth-offchain"
version = "0.5.4"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "FRAME pallet to relay Ethereum header automactically"
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia/"

[dependencies]
# crates
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
# darwinia
darwinia-eth-relay = { default-features = false, path = "../relay" }
darwinia-support = { default-features = false, path = "../../../../frame/support" }
eth-primitives = { default-features = false, path = "../../../../primitives/eth-primitives" }
# github
rlp = { default-features = false, git = "https://github.com/darwinia-network/parity-common.git" }
# substrate
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.5" }
frame-system = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.5" }
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.5" }
sp-std = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.5" }

[dev-dependencies]
# crates
serde_json = { version = "1.0.51" }
# substrate
sp-core = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.5" }
sp-io = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.5" }

[features]
default = ["std"]
std = [
	# crates
	"codec/std",
	# darwinia
	"darwinia-eth-relay/std",
	"darwinia-support/std",
	"eth-primitives/std",
	# github
	"rlp/std",
	# substrate
	"frame-support/std",
	"frame-system/std",
	"sp-runtime/std",
	"sp-std/std",
]
