[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Node-specific RPC methods for interaction with header-mmr."
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-header-mmr-rpc"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "1.0.0-alpha.1"

[dependencies]
# crates
codec               = { package = "parity-scale-codec", version = "1.3.4" }
jsonrpc-core        = "14.2.0"
jsonrpc-core-client = "14.2.0"
jsonrpc-derive      = "14.2.1"
# darwinia
darwinia-header-mmr-rpc-runtime-api = { path = "./runtime-api" }
# substrate
sp-api        = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sp-blockchain = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sp-runtime    = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
