[package]
name = "darwinia-header-mmr-rpc"
version = "0.6.1"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Node-specific RPC methods for interaction with header-mmr."
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia-common/"

[dependencies]
# crates
codec = { package = "parity-scale-codec", version = "1.3.1" }
jsonrpc-core = "14.2.0"
jsonrpc-core-client = "14.2.0"
jsonrpc-derive = "14.2.1"
# darwinia
darwinia-header-mmr-rpc-runtime-api = { path = "./runtime-api" }
# substrate
sp-api = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.2" }
sp-blockchain = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.2" }
sp-runtime = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.2" }
