[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "RPC traits of Ethereum."
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "dvm-rpc-core-primitives"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "1.2.2"

[dependencies]
# crates
ethereum-types      = "0.9.0"
jsonrpc-core        = "15.1.0"
jsonrpc-core-client = "15.1.0"
jsonrpc-derive      = "15.1.0"
jsonrpc-pubsub      = "15.1.0"
rustc-hex           = "2.1.0"
serde               = { version = "1.0", features = ["derive"] }
serde_json          = "1.0"
