[package]
name = "darwinia-staking-rpc-runtime-api"
version = "0.6.4"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Runtime API definition required by staking RPC extensions."
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia-common/"

[dependencies]
# crates
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }
serde = { version = "1.0.115", optional = true, features = ["derive"] }
# darwinia
darwinia-support = { default-features = false, path = "../../../support" }
# substrate
sp-api = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.4" }
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.4" }

[features]
default = ["std"]
std = [
	# crates
	"codec/std",
	"serde",
	# darwinia
	"darwinia-support/std",
	# substrate
	"sp-api/std",
	"sp-runtime/std",
]
