[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Ethereum Primitives"
edition     = "2021"
homepage    = "https://darwinia.network"
license     = "GPL-3.0"
name        = "ethereum-primitives"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common"
version     = "2.8.3"

[dependencies]
# crates.io
array-bytes     = { version = "1.4" }
codec           = { package = "parity-scale-codec", version = "2.2", optional = true, default-features = false, features = ["derive"] }
ethbloom        = { version = "0.11", default-features = false }
ethereum-types  = { version = "0.12", default-features = false }
keccak-hash     = { version = "0.8", default-features = false }
rlp             = { version = "0.5", optional = true, default-features = false }
rlp-derive      = { version = "0.1", optional = true }
scale-info      = { version = "1.0", optional = true, default-features = false, features = ["derive"] }
serde           = { version = "1.0", optional = true, features = ["derive"] }
sp-debug-derive = { version = "3.0" }
subhasher       = { version = "0.1", default-features = false }
# darwinia-network
ethash               = { default-features = false, git = "https://github.com/darwinia-network/rust-ethash", tag = "v0.4.2" }
merkle-patricia-trie = { default-features = false, path = "../merkle-patricia-trie" }

[dev-dependencies]
# crates.io
array-bytes    = { version = "1.4", features = ["serde"] }
codec          = { package = "parity-scale-codec", version = "2.2", features = ["derive"] }
ethbloom       = { version = "0.11", features = ["codec"] }
ethereum-types = { version = "0.12", features = ["codec"] }
keccak-hasher  = { version = "0.15" }
rlp            = { version = "0.5" }
rlp-derive     = { version = "0.1" }
serde          = { version = "1.0", features = ["derive"] }
serde_json     = { version = "1.0" }
triehash       = { version = "0.8" }

[features]
default = ["std"]

std = [
	# crates.io
	"ethbloom/std",
	"ethereum-types/std",
	"keccak-hash/std",
	"sp-debug-derive/std",
	"subhasher/std",
	# darwinia-network
	"ethash/std",
	"merkle-patricia-trie/std",
]

full-codec = [
	"codec",
	"ethbloom/codec",
	"ethereum-types/codec",
	"scale-info",
]

full-rlp = [
	"rlp",
	"rlp-derive",
	"ethbloom/rlp",
	"ethereum-types/rlp",
]

full-serde = [
	"array-bytes/serde",
	"serde",
	"ethbloom/serialize",
	"ethereum-types/serialize",
]

dag = []
