[package]
authors     = ["Anonymous"]
build       = "build.rs"
description = "Darwinia Node template"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "Unlicense"
name        = "node-template"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "1.0.0-alpha.1"

[[bin]]
name = "node-template"

[dependencies]
# anonymous
node-template-runtime = { path = "../runtime" }
# crates
codec        = { package = "parity-scale-codec", version = "1.3.4" }
futures      = { version = "0.3.5" }
jsonrpc-core = { version = "14.2.0" }
log          = { version = "0.4.11" }
structopt    = { version = "0.3.16" }
tokio        = { version = "0.2.22", optional = true, features = ["rt-threaded"] }
# darwinia
darwinia-balances-rpc               = { path = "../../../frame/balances/rpc" }
darwinia-balances-rpc-runtime-api   = { path = "../../../frame/balances/rpc/runtime-api" }
darwinia-claims                     = { path = "../../../frame/claims" }
darwinia-cli                        = { optional = true, path = "../../../client/cli" }
darwinia-ethereum-linear-relay      = { path = "../../../frame/bridge/ethereum/linear-relay" }
darwinia-ethereum-relay             = { path = "../../../frame/bridge/ethereum/relay" }
darwinia-header-mmr-rpc             = { path = "../../../frame/header-mmr/rpc" }
darwinia-header-mmr-rpc-runtime-api = { path = "../../../frame/header-mmr/rpc/runtime-api" }
darwinia-staking                    = { path = "../../../frame/staking" }
darwinia-staking-rpc                = { path = "../../../frame/staking/rpc" }
darwinia-staking-rpc-runtime-api    = { path = "../../../frame/staking/rpc/runtime-api" }
# substrate
frame-system-rpc-runtime-api               = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
pallet-im-online                           = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
pallet-transaction-payment-rpc             = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sc-basic-authorship                        = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sc-cli                                     = { optional = true, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sc-client-api                              = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sc-consensus                               = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sc-consensus-babe                          = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sc-consensus-babe-rpc                      = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sc-consensus-epochs                        = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sc-executor                                = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sc-finality-grandpa                        = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sc-finality-grandpa-rpc                    = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sc-keystore                                = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sc-network                                 = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sc-rpc                                     = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sc-rpc-api                                 = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sc-service                                 = { optional = true, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sc-transaction-pool                        = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sp-api                                     = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sp-authority-discovery                     = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sp-block-builder                           = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sp-blockchain                              = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sp-consensus                               = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sp-consensus-babe                          = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sp-core                                    = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sp-finality-grandpa                        = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sp-inherents                               = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sp-offchain                                = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sp-runtime                                 = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sp-session                                 = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sp-transaction-pool                        = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sp-trie                                    = { features = ["memory-tracker"], git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
substrate-frame-rpc-system                 = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
substrate-prometheus-endpoint              = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }

[build-dependencies]
# substrate
substrate-build-script-utils = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }

[features]
default = [
	"cli",
	"db",
	"full-node",
	"wasmtime",
]

cli       = [
	"tokio",
	"darwinia-cli",
	"sc-cli",
	"sc-service",
]
db        = ["sc-service/db"]
full-node = []
wasmtime  = ["sc-cli/wasmtime"]
