[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "millau node bridge primitives"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "millau-bridge-primitives"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "2.5.0"

[dependencies]
# bridge
bp-messages = { default-features = false, git = "https://github.com/darwinia-network/parity-bridges-common", branch = "main" }
bp-runtime  = { default-features = false, git = "https://github.com/darwinia-network/parity-bridges-common", branch = "main" }
# darwinia
drml-primitives = { default-features = false, path = "../../primitives" }
# substrate
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
frame-system = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sp-api        = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sp-core       = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sp-runtime    = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }
sp-std        = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "main" }

[features]
default = ["std"]

std = [
	"darwinia-std",
	"substrate-std",
]

darwinia-std = [
	"drml-primitives/std",
]

substrate-std = [
	"bp-messages/std",
	"bp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"sp-api/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
