[package]
name = "darwinia-cli"
version = "1.0.0-alpha.1"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia CLI interface."
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia-common/"

[dependencies]
# crates
serde = { version = "1.0.115", features = ["derive"] }
toml = { version = "0.5.6" }
# substrate
sc-cli = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sc-client-api = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sc-service = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
sc-tracing = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-darwinia-rc5" }
