[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia CLI interface."
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-cli"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "1.0.0-alpha.3"

[dependencies]
# crates
serde = { version = "1.0.115", features = ["derive"] }
toml  = { version = "0.5.6" }
# substrate
sc-cli        = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sc-client-api = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sc-service    = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sc-tracing    = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
