[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Storage key for ethereum schema"
edition     = "2021"
homepage    = "https://darwinia.network"
license     = "GPL-3.0"
name        = "dp-storage"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common"
version     = "2.7.2"

[dependencies]

[features]
default = ["std"]

std = []
