[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Pangolin node bridge primitives"
edition     = "2021"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "drml-bridge-primitives"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "2.7.1"

[dependencies]
# darwinia-network
darwinia-fee-market    = { default-features = false, path = "../../../frame/fee-market" }
drml-common-primitives = { default-features = false, path = "../common" }
# paritytech
bp-messages            = { default-features = false, git = "https://github.com/darwinia-network/parity-bridges-common", branch = "realtime-version-darwinia" }
bp-runtime             = { default-features = false, git = "https://github.com/darwinia-network/parity-bridges-common", branch = "realtime-version-darwinia" }
bridge-runtime-common  = { default-features = false, git = "https://github.com/darwinia-network/parity-bridges-common", branch = "realtime-version-darwinia" }
frame-support          = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.7" }
pallet-bridge-dispatch = { default-features = false, git = "https://github.com/darwinia-network/parity-bridges-common", branch = "realtime-version-darwinia" }
sp-api                 = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.7" }
sp-core                = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.7" }
sp-runtime             = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.7" }
sp-std                 = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.7" }

[features]
default = ["std"]

std = [
	# darwinia-network
	"darwinia-fee-market/std",
	"drml-common-primitives/std",
	# paritytech
	"bp-messages/std",
	"bp-runtime/std",
	"bridge-runtime-common/std",
	"pallet-bridge-dispatch/std",
	"frame-support/std",
	"sp-api/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
