[package]
name = "darwinia-eth-backing"
version = "0.5.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "FRAME pallet to backing Ethereum assets"
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia/"

[dependencies]
# crates
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true }
# darwinia
darwinia-eth-relay = { default-features = false, path = "../relay" }
darwinia-support = { default-features = false, path = "../../../support" }
eth-primitives = { default-features = false, path = "../../../../primitives/eth-primitives" }
# github
ethabi = { default-features = false, git = "https://github.com/darwinia-network/ethabi.git", branch = "with_no_std" }
# substrate
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.2" }
frame-system = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.2" }
sp-core = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.2" }
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.2" }
sp-std = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.2" }

[dev-dependencies]
# crates
hex-literal = { version = "0.2.1" }
rustc-hex = { version = "2.0" }
# darwinia
pallet-ring = { package = "darwinia-ring", path = "../../../../frame/balances/ring" }
pallet-staking = { package = "darwinia-staking", path = "../../../../frame/staking" }
# github
rlp = { package = "rlp", git = "https://github.com/darwinia-network/parity-common.git" }
# substrate
pallet-session = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.2" }
pallet-timestamp = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.2" }
sp-io = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.2" }
sp-staking = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-alpha.darwinia.2" }

[features]
default = ["std"]
std = [
	# crates
	"codec/std",
	"serde",
	# darwinia
	"darwinia-eth-relay/std",
	"darwinia-support/std",
	"eth-primitives/std",
	# github
	"ethabi/std",
	# substrate
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
