[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Empty mock precompiles for EVM pallet."
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-evm-precompile-empty"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "1.4.0"

[dependencies]
# crates
darwinia-evm-primitives = { default-features = false, path = "../../../../../primitives/evm" }
evm                     = { version = "0.23.0", default-features = false, features = ["with-codec"] }

[features]
default = ["std"]

std = [
	"crates-std",
]

crates-std = [
	"darwinia-evm-primitives/std",
	"evm/std",
]
